services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
    networks:
      - app_network

  database:
    image: "postgres:17"
    restart: always
    # Shared memory
    shm_size: 1g

    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-SuperSecretProdPassword}
      POSTGRES_DB: ${DB_NAME:-webapp_prod}
      POSTGRES_INITDB_ARGS: "--data-checksums" # Data Integrity

    # Bind only to localhost
    ports:
      - "127.0.0.1:5432:5432"

    # Persistant storage
    volumes:
      - pg_data:/var/lib/postgresql/data

    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 4G
        reservations:
          cpus: "1"
          memory: 1G

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

    networks:
      - app_network

  backend:
    build:
      context: ./backend
    restart: always
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://${DB_USER:-admin}:${DB_PASSWORD:-SuperSecretProdPassword}@database:5432/${DB_NAME:-webapp_prod}
      - RUST_LOG=info,vaultchat=debug
    networks:
      - app_network

volumes:
  pg_data:

networks:
  app_network:
    driver: bridge
